const Router = require('express')
const router = new Router()
const competitionController = require('../controllers/competitionController')
const checkRole = require('../middleware/CheckRoleMiddleware')


router.get('/', competitionController.getAll)
router.get('/current/:id', competitionController.getCurrent)
router.patch('/current/:id', checkRole('ADMIN,MODERATOR'), competitionController.modify)
router.post('/', checkRole('ADMIN'), competitionController.create)
router.delete('/current/:id', checkRole('ADMIN'), competitionController.delete)
router.post('/img/', checkRole('ADMIN,MODERATOR'), competitionController.addImg)
router.get('/img/:competitionId', competitionController.getCompetitionImages)
router.delete('/img/:id', checkRole('ADMIN,MODERATOR'), competitionController.delImg)
router.post('/trick/', checkRole('ADMIN,MODERATOR'), competitionController.addTrick)
router.get('/trick/:id', competitionController.getTrick)
router.get('/trick/all/:competitionId', competitionController.getAllTricks)
router.delete('/trick/:id', checkRole('ADMIN,MODERATOR'), competitionController.deleteTrick)
router.delete('/trick/all/:competitionId', checkRole('ADMIN,MODERATOR'), competitionController.deleteAllCompetitionTricks)
router.post('/trick/all/', checkRole('ADMIN,MODERATOR'), competitionController.addAllCompetitionTricks)
router.patch('/trick/:id', checkRole('ADMIN,MODERATOR'), competitionController.modifyTrick)
router.post('/modifier/', checkRole('ADMIN,MODERATOR'), competitionController.addModifier)
router.get('/modifier/current/:competitionId', competitionController.getModifier)
router.delete('/modifier/current/:id',checkRole('ADMIN,MODERATOR'), competitionController.deleteModifier)
router.patch('/modifier/current/:id', checkRole('ADMIN,MODERATOR'), competitionController.modifyModifier)
router.post('/referee/', checkRole('ADMIN,MODERATOR'), competitionController.addReferee)
router.get('/referee/:competitionId', competitionController.getReferee)
router.delete('/referee/:id', checkRole('ADMIN,MODERATOR'), competitionController.deleteReferee)


module.exports = router