const Router = require('express')
const router = new Router()
const competitionController = require('../controllers/competitionController')
const checkRole = require('../middleware/CheckRoleMiddleware')


router.get('/', competitionController.getAll)
router.get('/current/:id', competitionController.getCurrent)
router.patch('/current/:id', checkRole('ADMIN'), competitionController.modify)
router.post('/', competitionController.create)
router.delete('/current/:id', checkRole('ADMIN'), competitionController.delete)
router.post('/img/', checkRole("ADMIN"), competitionController.addImg)
router.get('/img/:competitionId', competitionController.getCompetitionImages)
router.delete('/img/:id', checkRole("ADMIN"), competitionController.delImg)
router.post('/trick/', checkRole("ADMIN"), competitionController.addTrick)
router.get('/trick/:id', competitionController.getTrick)
router.get('/trick/all/:competitionId', competitionController.getAllTricks)
router.delete('/trick/:id', checkRole("ADMIN"), competitionController.deleteTrick)
router.delete('/trick/all/:competitionId', checkRole("ADMIN"), competitionController.deleteAllCompetitionTricks)
router.post('/trick/all/', checkRole("ADMIN"), competitionController.addAllCompetitionTricks)
router.patch('/trick/:id', checkRole("ADMIN"), competitionController.modifyTrick)
router.post('/modifier/', checkRole("ADMIN"), competitionController.addModifier)
router.get('/modifier/current/:competitionId', competitionController.getModifier)
router.delete('/modifier/current/:id', checkRole("ADMIN"), competitionController.deleteModifier)
router.patch('/modifier/current/:id', checkRole("ADMIN"), competitionController.modifyModifier)
router.post('/referee/', checkRole("ADMIN"), competitionController.addReferee)
router.get('/referee/:competitionId', competitionController.getReferee)
router.delete('/referee/:id', checkRole("ADMIN"), competitionController.deleteReferee)


module.exports = router