const Router = require('express')
const router = new Router()
const heatController = require('../controllers/heatController')
const checkRole = require('../middleware/CheckRoleMiddleware')


router.get('/current/:id', heatController.get)
router.patch('/current/:id', checkRole('ADMIN,MODERATOR'), heatController.modify)
router.post('/', checkRole('ADMIN,MODERATOR'), heatController.create)
router.delete('/current/:id', checkRole('ADMIN,MODERATOR'), heatController.delete)
router.get('/team_heat/:id', heatController.getTeamHeat)
router.patch('/team_heat/:id', checkRole('ADMIN,MODERATOR'), heatController.modifyTeamHeat)
router.post('/team_heat/', checkRole('ADMIN,MODERATOR'), heatController.createTeamHeat)
router.post('/group/', checkRole('ADMIN,MODERATOR'), heatController.createFirstGroupHeats)
router.post('/next/', checkRole('ADMIN,MODERATOR'), heatController.createNextRoundsHeats)
router.post('/team_next/', checkRole('ADMIN,MODERATOR'), heatController.createNextRoundTeamHeats)
router.get('/group/:groupId', heatController.getGroupHeats)
router.get('/group_team/:groupId', heatController.getTeamGroupHeats)
router.delete('/team_heat/:id', checkRole('ADMIN,MODERATOR'), heatController.deleteTeamHeat)
router.post('/calculate_heat/:id', checkRole('ADMIN,MODERATOR'), heatController.heatCalculate)
router.post('/calculate_team_heat/:id', checkRole('ADMIN,MODERATOR'), heatController.teamHeatCalculate)
router.get('/trick/:id', heatController.getTrick)
router.patch('/trick/:id', checkRole('ADMIN,MODERATOR'), heatController.modifyTrick)
router.post('/trick', checkRole('ADMIN,MODERATOR'), heatController.addTrick)
router.post('/calculate_trick/:id', checkRole('ADMIN,MODERATOR'), heatController.trickCalculate)
router.delete('/trick/:id', checkRole('ADMIN,MODERATOR'), heatController.deleteTrick)
router.patch('/modifier/:id', checkRole('ADMIN,MODERATOR'), heatController.editTrickModifier)


module.exports = router